# cfgs/default.yaml

# ======================
# Data configuration
# ======================
data:
  trainloader:
    name: date
    params:
      file: fake_data.parquet
      fillna: zero
      dffilter: null
      normalize: null

  validloader:
    name: date
    params:
      file: fake_data.parquet
      fillna: zero
      dffilter: null
      normalize: null

  evalloader:
    name: date
    params:
      file: fake_data.parquet
      fillna: zero
      dffilter: null
      normalize: null

  label:
    - y
  features: fake.pkl
  eqtydata: EqtyData.pkl


# ======================
# Model configuration
# ======================
model:
  name: mlp
  params:
    # feature_dim: 450
    hidden_dims: [32]
    dropout: 0.1
    init: xavier   # Reserved: xavier / normal / kaiming


# ======================
# Loss configuration
# ======================
loss:
  name: mse
  params: {}


# ======================
# Training configuration
# ======================
train:
  epochs: 1
  lr: 0.001
  device: cpu
  record: False
  logdir: tensorboard
  # scheduler:
  #   name: StepLR
  #   params:
  #     step_size: 10
  #     gamma: 0.1
  early_stop:
    patience: 1
    monitor: val_loss


# ======================
# Evaluating configuration
# ======================
eval:
  device: cpu
  record: False
  logdir: tensorboard


# ======================
# Metric configuration
# ======================
# metric:
#   name: rmse
#   params: {}


# end of cfgs/default.yaml