# cfgs/default.yaml

# ======================
# Data configuration
# ======================
data:
  traindata:
    file: fake_data.parquet
    filter: null

  validdata:
    file: fake_data.parquet
    filter: null
    # filter: "date >= '2020-01-03'"

  testdata:
    file: fake_data.parquet
    filter: null

  label:
    - y
  features: fake.pkl
  eqtydata: EqtyData.pkl


# ======================
# Model configuration
# ======================
model:
  name: mlp
  params:
    hidden_dim: 32
    init: xavier   # Reserved: xavier / normal / kaiming


# ======================
# Loss configuration
# ======================
loss:
  name: mse
  params: {}


# ======================
# Training configuration
# ======================
train:
  epochs: 4
  lr: 0.001
  device: cpu
  record: True
  logdir: tensorboard
  # scheduler:
  #   name: StepLR
  #   params:
  #     step_size: 10
  #     gamma: 0.1
  early_stop:
    patience: 1
    monitor: val_loss


# ======================
# Result configuration
# ======================
result:
  file: null
  score: null


# ======================
# Metric configuration
# ======================
# metric:
#   name: rmse
#   params: {}


# end of cfgs/default.yaml