# cfgs/ictrain.yaml

# ======================
# Data configuration
# ======================
data:
  trainloader:
    name: interval
    params:
      file: fake_data.parquet
      fillna: zero
      dffilter: null
      normalize: zscore

  validloader:
    name: interval
    params:
      file: fake_data.parquet
      fillna: zero
      dffilter: "date >= '2020-01-03'"
      normalize: zscore

  evalloader:
    name: interval
    params:
      file: fake_data.parquet
      fillna: zero
      dffilter: null
      normalize: zscore

  label:
    - y
  features: fake.pkl
  eqtydata: EqtyData.pkl


# ======================
# Model configuration
# ======================
model:
  name: icmlp
  params:
    # feature_dim: 450
    hidden_dims: [32]
    dropout: 0.1
    init: xavier


# ======================
# Loss configuration
# ======================
loss:
  name: pearsonic
  params: {}


# ======================
# Training configuration
# ======================
train:
  epochs: 10
  lr: 0.001
  device: cpu
  record: False
  logdir: tensorboard
  checkpoint:
    save_latest: True
    save_best: True
  scheduler:
    name: StepLR
    params:
      step_size: 5
      gamma: 0.5
  early_stop:
    patience: 5
    monitor: val_loss


# ======================
# Evaluating configuration
# ======================
eval:
  device: cpu
  record: True
  logdir: ic


# ======================
# Metric configuration
# ======================
metric:
  name: null
  params: {}


# ======================
# Reserved configuration
# ======================
ic:
  mask_source: label_nan  # 当前实现
  future_shift: 1         # 未来 horizon
  weight: null            # 未来 sample weighting


# end of cfgs/ictrain.yaml