# cfgs/ictrain.yaml

# ======================
# Data configuration
# ======================
data:
  trainloader:
    name: interval
    params:
      file: fake_data.parquet
      fillna: zero
      dffilter: null
      normalize: zscore

  validloader:
    name: interval
    params:
      file: fake_data.parquet
      fillna: zero
      dffilter: "date >= '2020-01-03'"
      normalize: zscore

  evalloader:
    name: interval
    params:
      file: fake_data.parquet
      fillna: zero
      dffilter: null
      normalize: zscore

  label:
    - y
  features: fake.pkl
  eqtydata: EqtyData.pkl


# ======================
# Model configuration
# ======================
model:
  name: icmlp
  params:
    # feature_dim: 450
    hidden_dims: [32]
    dropout: 0.1
    init: xavier


# ======================
# Loss configuration
# ======================
loss:
  name: pearsonic
  params: {}


# ======================
# Metric configuration
# ======================
metric:
  pearsonic: {}
  spearmanic: {}
  top:
    k: 2


# ======================
# Training configuration
# ======================
train:
  epochs: 10
  lr: 0.001
  optimizer:
    name: Adam
    params:
      weight_decay: 0.0001
  scheduler:
    name: StepLR
    params:
      step_size: 5
      gamma: 0.5
  device: cpu
  record: True
  logdir: tensorboard
  early_stop:
    patience: 5
    monitor:
      - pearsonic
      - top
  checkpoint:
    save_best: True
    save_latest: True
    save_every_step: True


# ======================
# Evaluating configuration
# ======================
eval:
  device: cpu
  record: True
  logdir: ic


# end of cfgs/ictrain.yaml